### ISSUE TITLE
Cannot install package with npm@10.7.0

### ISSUE THREAD

**Issue by nghiahung-dev** [cassidoo/blahg#18]
### Enviroments
- npm@10.7.0
- node@22.1.0

### Errors
Issue by `better-sqlite3@8.7.0` package. 
```
189 error path /Users/nnhjs/Desktop/sideProject/handbook/node_modules/better-sqlite3
190 error command failed
191 error command sh -c prebuild-install || node-gyp rebuild --releas
```

**Comment by bhavaniravi** [comment]
@nnhjs Were you able to fix this?

**Comment by cassidoo** [comment]
Hey @nnhjs and @bhavaniravi, just pushed some updates to packages that I *think* should solve this, mind trying again?
