### ISSUE TITLE
Misplaced Footer

### ISSUE THREAD

**Issue by Lou8is** [cassidoo/blahg#19]
On the posts.astro file, <Footer /> is placed inside of <main> (see https://github.com/cassidoo/blahg/blob/0d03ec770f660c2309a5482ef4f10860f26705ab/src/pages/posts.astro#L43)

However, it is placed outside of it in index.astro for instance.

Nothing too bad but it caused me some CSS issues while fidgeting, you might want to change that.

**Comment by cassidoo** [comment]
Thanks for this, good catch!
