### ISSUE TITLE
HeaderLink titles not properly showing active

### ISSUE THREAD

**Issue by mjr2595** [cassidoo/blahg#21]
How it do, Cassidoo?

I'm using this as inspo / starting off point for my blog and I'm noticing the same issue for my blog and this template:

When on any other page besides 'home', the header link title is not bold and underlined.

![image](https://github.com/user-attachments/assets/a796ce94-7eb8-4dae-9f17-d500db4c50db)

I'm working on fixing this within my repo and will def submit a PR if I find the fix, but I wanted to post in here in case you or someone else beats me to it. I'm still learning Astro and so not sure how long I'll take to figure this out.

Interestingly, it does work locally... just not when deployed. I'm also deploying on Netlify.

**Comment by cassidoo** [comment]
Fixed, thanks for reporting @mjr2595!

**Comment by mjr2595** [comment]
Of course! haha nice catch. I kinda forgot about this. Thanks @cassidoo
